using System;
using System.Linq;
using System.Text;

namespace DbDocGeneratorUI
{
    public class MarkdownGenerator
    {
        public string Generate(DatabaseSchema schema, string schemaFilter)
        {
            var tables = schema.GetTables(schemaFilter);
            var sb = new StringBuilder();

            sb.AppendLine("# Documentation for database: " + schema.DatabaseName);
            sb.AppendLine();
            sb.AppendLine("> Technical documentation of database schema");
            sb.AppendLine();
            sb.AppendLine("| Parameter | Value |");
            sb.AppendLine("|-----------|-------|");
            sb.AppendLine("| Server | " + schema.Server + " |");
            sb.AppendLine("| Database | " + schema.DatabaseName + " |");
            sb.AppendLine("| Schema | " + schemaFilter + " |");
            sb.AppendLine("| Generated | " + DateTime.Now.ToString("dd.MM.yyyy HH:mm:ss") + " |");
            sb.AppendLine();
            sb.AppendLine("---");
            sb.AppendLine();

            sb.AppendLine("## Table of Contents");
            sb.AppendLine();
            for (int i = 0; i < tables.Count; i++)
                sb.AppendLine((i + 1) + ". [" + tables[i].SchemaName + "." + tables[i].TableName + "](#tab-" + i + ")");
            sb.AppendLine();
            sb.AppendLine("---");
            sb.AppendLine();

            for (int i = 0; i < tables.Count; i++)
            {
                var table = tables[i];
                sb.AppendLine("### " + (i + 1) + ". Table: `" + table.SchemaName + "." + table.TableName + "`");
                sb.AppendLine();
                if (!string.IsNullOrEmpty(table.Description))
                {
                    sb.AppendLine(table.Description);
                    sb.AppendLine();
                }

                sb.AppendLine("| # | Column Name | Type | Null | Default | Description |");
                sb.AppendLine("|---|-------------|------|------|---------|-------------|");

                foreach (var col in table.Columns)
                {
                    var pkMark = table.PrimaryKey?.Columns.Contains(col.ColumnName) == true ? " PK" : "";
                    var fkMark = table.ForeignKeys.Any(fk => fk.Columns.Contains(col.ColumnName)) ? " FK" : "";
                    var typeStr = FormatDataType(col);
                    sb.AppendLine("| " + col.OrdinalPosition + " | `" + col.ColumnName + "`" + pkMark + fkMark + " | `" + typeStr + "` | " + (col.IsNullable ? "Yes" : "No") + " | " + (!string.IsNullOrEmpty(col.DefaultValue) ? col.DefaultValue : "\u2014") + " | " + (string.IsNullOrEmpty(col.Description) ? "\u2014" : col.Description) + " |");
                }

                sb.AppendLine();

                if (table.PrimaryKey != null && table.PrimaryKey.Columns.Count > 0)
                {
                    sb.AppendLine("**Primary Key:**");
                    sb.AppendLine();
                    sb.AppendLine("`" + string.Join(", ", table.PrimaryKey.Columns) + "`");
                    sb.AppendLine();
                }

                if (table.ForeignKeys.Count > 0)
                {
                    sb.AppendLine("**Foreign Keys:**");
                    sb.AppendLine();
                    sb.AppendLine("| Constraint | Columns | References | ON UPDATE | ON DELETE |");
                    sb.AppendLine("|------------|---------|------------|-----------|-----------|");
                    foreach (var fk in table.ForeignKeys)
                        sb.AppendLine("| `" + fk.ConstraintName + "` | `" + string.Join(", ", fk.Columns) + "` | " + fk.ReferencedSchema + "." + fk.ReferencedTable + " (" + string.Join(", ", fk.ReferencedColumns) + ") | " + (fk.OnUpdate ?? "NO ACTION") + " | " + (fk.OnDelete ?? "NO ACTION") + " |");
                    sb.AppendLine();
                }

                if (table.Indexes.Count > 0)
                {
                    sb.AppendLine("**Indexes:**");
                    sb.AppendLine();
                    sb.AppendLine("| Index Name | Unique | Columns |");
                    sb.AppendLine("|------------|--------|---------|");
                    foreach (var idx in table.Indexes)
                        sb.AppendLine("| `" + idx.IndexName + "`" + (idx.IsPrimaryKey ? " [PK]" : "") + (idx.IsUniqueConstraint ? " [UC]" : "") + " | " + (idx.IsUnique ? "Yes" : "No") + " | `" + string.Join(", ", idx.Columns) + "` |");
                    sb.AppendLine();
                }

                sb.AppendLine("---");
                sb.AppendLine();
            }

            sb.AppendLine();
            sb.AppendLine("*Documentation generated by DbDocGenerator | " + DateTime.Now.ToString("dd.MM.yyyy HH:mm") + "*");
            return sb.ToString();
        }

        private string FormatDataType(ColumnInfo col)
        {
            var type = col.DataType;
            switch (type.ToLower())
            {
                case "varchar": case "nvarchar": case "char": case "nchar":
                    if (col.CharacterMaximumLength.HasValue && col.CharacterMaximumLength.Value == -1) return type + "(MAX)";
                    if (col.CharacterMaximumLength.HasValue) return type + "(" + col.CharacterMaximumLength + ")";
                    return type;
                case "decimal": case "numeric":
                    if (col.NumericPrecision.HasValue && col.NumericScale.HasValue) return type + "(" + col.NumericPrecision + "," + col.NumericScale + ")";
                    return type;
                default: return type;
            }
        }
    }
}